i-Cell-Mobilsoft-Open-Source/icell-data-table

src/server-side/server-side-data-source.ts

fix(serverSideDataSource): Observable logic refactored

---

package-lock.json
package.json

- ng-dynamic-component referenced for angular 10

fix(dependency-slip)

---

README.adoc
src/cell-templates/cell-templates.component.html
src/cell-templates/cell-templates.component.ts
src/index.ts
src/interfaces/component-options.interface.ts
src/interfaces/data-table-column-definition.interface.ts
src/interfaces/index.ts

feat(componentTemplate): Provide input, output bindings

---

src/data-table.component.html

change needed because of accessibility reason

fix(dataTable): change div to button in expand collapse detail row

---

README.adoc
examples/icell-data-table-example/src/app/app.component.html
examples/icell-data-table-example/src/app/app.component.ts
examples/icell-data-table-example/src/app/app.module.ts
package.json
src/data-table.component.html
src/data-table.component.scss
src/data-table.component.ts
src/interfaces/data-table-column-definition.interface.ts
src/server-side/server-side-data-source.ts

* feat(a11y) enhancements
- #70 custom sort in header
- #71 identifier cell
* fix(dataSource)
- moved to get/set
* chore(comment)
- added comment in example
* Delete README.md
* typo
* fix(scss) wrapped into component
Co-authored-by: Onofer Dávid <david.onofer@icellmobilsoft.hu>

feat(a11y) enhancements (#72)

---

README.adoc
package.json
src/cell-templates/cell-templates.component.html
src/data-table.component.html
src/data-table.component.ts
src/data-table.module.ts
src/index.ts
src/interfaces/data-table-column-definition.interface.ts
src/pipes/sanitize.pipe.ts

- added property to set custom classes for headers

enhancement(#82)

---

README.adoc
package.json
src/cell-templates/cell-templates.component.html
src/data-table.component.html
src/data-table.component.ts
src/data-table.module.ts
src/index.ts
src/interfaces/data-table-column-definition.interface.ts
src/pipes/sanitize.pipe.ts

* enhancement(#82)
- added property to set custom classes for headers
* enhancement(#82)
- added property to set custom classes for cells
- `@Input` for header row classes
* enhancement(#82)
- added sanitize pipe for translation with html
Co-authored-by: Onofer Dávid <david.onofer@icellmobilsoft.hu>

Release 1.0.24

---

package.json
src/data-table.component.html
src/data-table.component.ts
src/index.ts
src/interfaces/data-table-column-settings.interface.ts
src/interfaces/data-table-grouping-header.interface.ts

enhancement(grouping-header)

---

src/cell-templates/cell-templates.component.html

Noticed a small mistake around the `aria-label` of the icon.

Fixed improper binding

---

examples/icell-data-table-example/package-lock.json
examples/icell-data-table-example/package.json
package-lock.json
package.json

Updated the `ng-dynamic-component` dependency version, to support Angular 11 properly. https://www.npmjs.com/package/ng-dynamic-component

Updated ng-dynamic-component to support angular 11

---

scripts/readme-adoc2md

proposed fix for the issue mentioned in here: https://github.com/i-Cell-Mobilsoft-Open-Source/icell-data-table/issues/93

Install bash script fix

---

examples/icell-data-table-example/package-lock.json
examples/icell-data-table-example/package.json
examples/icell-data-table-example/src/app/app.component.html
examples/icell-data-table-example/src/app/table-demo.service.ts
package.json
src/data-table.component.html
src/data-table.component.ts

In this feature proposal, I introduce an attribute name variable, which can be used to individually hide/show the select boxes on each row if wanted.
I request your approval, as my current task requires this functionality in the ic-data-table.
I have updated the example project to show the new utility. 
The result looks like this:

Hide useSelection in specific rows functionality added

---

package.json
src/data-table.component.html

Co-authored-by: daniel.rudolf <daniel.rudolf@icellmobilsoft.hu>

fix(dataTable): set checkbox th role to cell (#143)

---

README.adoc
examples/icell-data-table-example/src/app/app.component.html
examples/icell-data-table-example/src/app/app.component.ts
package.json
src/data-table.component.html
src/data-table.component.ts

Removed the first solution, and extended documentation for hooking up onto filtering the correct way, using the built-in MatSort.

Updated custom filtering logic

---

README.adoc

Added an extra string for localization guide, which was not indicated previously. .

Update README.adoc - ICELL_DATA_TABLE.NOROWSTOSHOW

---

package.json
src/cell-templates/cell-templates.component.ts

fix(cellTemplates): display number 0 properly returned by valueGetter

---

package.json
src/data-table.component.ts
src/interfaces/column-selection-event.interface.ts

bugfix for column selection change emitter

---

package.json
src/data-table.component.html

fix(dataTable): improve table head template selection conditions

---

package.json
src/data-table.component.ts

save default column settings when the selected column menu is dragMenu #243
Signed-off-by: veresdaniel <veresdaniel@gmail.com>

fix(data-table) save default column settings

---

README.adoc
package.json
src/cell-templates/cell-templates.component.html
src/cell-templates/cell-templates.component.ts

- updated labelTemplate to use EMPTY_CELL localization value
- updated labelBoldTemplate to use EMPTY_CELL localization value

feat(EMPTY_CELL) changes
